[package]
name = "sid_vec"
version = "0.2.0"
description = "Tiny library providing id types and an id-based vector."
license = "MIT/Apache-2.0"
authors = [ "Nicolas Silva <nical@fastmail.com>" ]
repository = "https://github.com/nical/vodk.rs"

[lib]

name = "sid_vec"
